services:
  customermanagementapi:
    image: ${DOCKER_REGISTRY-}customermanagementapi
    build:
      context: .
      dockerfile: CustomerManagementAPI/Dockerfile
    ports:
      - "7163:7163"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:7163
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server   
    container_name: sqlms
    hostname: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword1
    restart: unless-stopped
    ports:
      - "1401:1433"
